//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BooksList.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book author:.
        /// </summary>
        public static string AddAuthor {
            get {
                return ResourceManager.GetString("AddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick cover image.
        /// </summary>
        public static string AddCoverImg {
            get {
                return ResourceManager.GetString("AddCoverImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit position.
        /// </summary>
        public static string AddEditPositionTitle {
            get {
                return ResourceManager.GetString("AddEditPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add position.
        /// </summary>
        public static string AddNewPositionTitle {
            get {
                return ResourceManager.GetString("AddNewPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddSave {
            get {
                return ResourceManager.GetString("AddSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book title:.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing year:.
        /// </summary>
        public static string AddYear {
            get {
                return ResourceManager.GetString("AddYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBooks.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string BookListAuthor {
            get {
                return ResourceManager.GetString("BookListAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to books list.
        /// </summary>
        public static string BookListText {
            get {
                return ResourceManager.GetString("BookListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing year:.
        /// </summary>
        public static string BookListYear {
            get {
                return ResourceManager.GetString("BookListYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item is selected..
        /// </summary>
        public static string DeletingItemsNoObject {
            get {
                return ResourceManager.GetString("DeletingItemsNoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting items.
        /// </summary>
        public static string DeletingItemsTitle {
            get {
                return ResourceManager.GetString("DeletingItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string DeletingItemsWarning {
            get {
                return ResourceManager.GetString("DeletingItemsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string MenuBarAdd {
            get {
                return ResourceManager.GetString("MenuBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string MenuBarDelete {
            get {
                return ResourceManager.GetString("MenuBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string MenuBarEdit {
            get {
                return ResourceManager.GetString("MenuBarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name can&apos;t be empty..
        /// </summary>
        public static string WarningAuthor {
            get {
                return ResourceManager.GetString("WarningAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t put some of the information..
        /// </summary>
        public static string WarningNoInfo {
            get {
                return ResourceManager.GetString("WarningNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book title can&apos;t be empty..
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing year can&apos;t be smaller than 0..
        /// </summary>
        public static string WarningYear {
            get {
                return ResourceManager.GetString("WarningYear", resourceCulture);
            }
        }
    }
}
